# ============================================================================ #
#                      Snake Animation Generation Workflow                     #
# ============================================================================ #
# This workflow generates a snake animation using the 'snk' action and pushes  #
# the generated files to the output branch.                                    #
#                                                                              #
# Key Specifications:                                                          #
#   - scheduled:     Runs every 12 hours at minute 0                           #
#   - output branch: 'output'                                                  #
#   - output files:  'dist/contr-grid-snake.svg'                               #
#                    'dist/contr-grid-snake-light.svg'                         #
#                                                                              #
# GitHub Action: https://github.com/Platane/snk                                #
# ============================================================================ #

name: "Snake Animation"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  schedule:
    # Runs every 12 hours at minute 0
    - cron: "0 */12 * * *"

jobs:
  # Generate snake animation
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: "Run: Generate snake animation"
        uses: Platane/snk@v3.4.1
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/contr-grid-snake.svg?color_snake=#ffffff&color_dots=#161b22,#4d525a,#6e7681,#8b949e,#f0f6fc
            dist/contr-grid-snake-light.svg?color_snake=#000000&color_dots=#d8dde2,#787b7e,#606264,#48494b,#303132
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Run: Push generated files to 'output' branch"
        uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          target_branch: "output"
          build_dir: "dist"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
