# ============================================================================ #
#                           Stats Generation Workflow                          #
# ============================================================================ #
# This workflow generates GitHub stats using the specified action and pushes   #
# the generated files to the output branch.                                    #
#                                                                              #
# Key Specifications:                                                          #
#   - scheduled:     Runs every 12 hours at minute 0                           #
#   - output branch: 'output'                                                  #
#   - output files:  'dist/stats.svg'                                          #
#                    'dist/stats-light.svg'                                    #
#                                                                              #
# Action: https://github.com/stats-organization/github-readme-stats-action     #
# ============================================================================ #

name: "Stats"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  schedule:
    # Runs every 12 hours at minute 0
    - cron: "0 */12 * * *"

jobs:
  # Generate GitHub stats
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write

    steps:
      - name: "Setup: Checkout repository"
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 1

      - name: "Run: Generate GitHub stats (dark)"
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: "username=${{ github.repository_owner }}&count_private=true&icon_color=fff&border_color=3d444d78&show_icons=true&theme=dark&border_radius=15&bg_color=39363f1e&title_color=fff&hide_title=true&line_height=28"
          path: "dist/stats.svg"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Run: Generate GitHub stats (light)"
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: "username=${{ github.repository_owner }}&count_private=true&icon_color=363636&border_color=dbe3eab3&show_icons=true&border_radius=15&bg_color=c5c5c91e&title_color=363636&hide_title=true&line_height=28"
          path: "dist/stats-light.svg"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Run: Push generated files to 'output' branch"
        uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          target_branch: "output"
          build_dir: "dist"
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
